export const GET_POKEMONS = "GET_POKEMONS";
export const GET_POKEMON_BY_NAME = "GET_POKEMON_BY_NAME";
export const GET_TYPES = "GET_TYPES";
export const FILTER_BY_TYPE = "FILTER_BY_TYPE";
export const FILTER_BY_ORIGIN = "FILTER_BY_ORIGIN";
export const ORDER_BY_NAME = "ORDER_BY_NAME";
export const ORDER_BY_ATTACK = "ORDER_BY_ATTACK";
export const GET_DETAIL = "GET_DETAIL";
export const RELOAD_POKEMONS = "RELOAD_POKEMONS";
export const RESET_DETAIL = "RESET_DETAIL";
export const POST_POKEMON = "POST_POKEMON";

//SON LOS NOMBRES DE NUESTRAS ACCIONES 